### ISSUE TITLE
allow both auction beneficiary and creator to claim

### ISSUE THREAD

**Issue by rainbeam** [rainbeam/token-auction#7]
Auctions might be created by a seller on behalf of a token holder. The seller should be able to claim on behalf of the token holder as well.

**Comment by nmushegian** [comment]
generally speaking anyone should be able to push tokens to their rightful owners. The thing to be concerned about is whether any particular address is expecting to receive tokens without notification.

**Comment by rainbeam** [comment]
I'm not sure that is the auction's problem. There would be event notification at least.

**Comment by nmushegian** [comment]
I don't understand. I'm making two different points:
1) "The seller should be able to claim on behalf of the token holder as well" -> "*anyone* should be able to claim on behalf of the token holder as well",  because why not? So anyone should be able to push (claim) to the actual owner.

2) We should NOT "push"/"claim" to an address which was not explicitly specified by someone via argument as an address which knows what to do when tokens are randomly deposited into it. In particular, if I use the token auction from a contract and my contract becomes the beneficiary, my contract also has to have the logic to push it along to wherever it goes afterwards. This is annoying because sometimes I want to just set the beneficiary to be a specific contract (like the MKR burner).

**Comment by rainbeam** [comment]
Sorry, thought you were talking about the more general problem of the beneficiary not knowing that they are going to benefit from an auction.

1) Yes, agreed. `claim` can be changed to be callable by anyone. All it requires is the auctionlet to be expired, then the action is to pay the winning bidder.

2) Yes, I believe this would be solved by having distinct beneficiary / creator.

**Comment by rainbeam** [comment]
superseded by #12
